### ISSUE TITLE
Не определяет город

### ISSUE THREAD

**Issue by vladios13** [AlexandrTyurikov/WeatherTelegramBot#1]
При введенных всех токенов, бот ни в какую ни при любом запросе не определяет город. 
Ни на русском, ни на английском. 
![bot-bug](https://user-images.githubusercontent.com/10531221/72816461-39ffdb80-3c79-11ea-8930-6b8a710ef264.jpg)

**Comment by AlexandrTyurikov** [comment]
Возможно, возможно, яндекс-API еще не прошол проверку

вт, 21 янв. 2020 г. в 18:10, vladios13 <notifications@github.com>:

**Comment by vladios13** [comment]
> не прошол проверку

Спустя несколько дней все заработало. Отлично, **большое спасибо!**
